import { Routes, Route, Navigate } from 'react-router-dom';
import { CalendarDays, Dumbbell, BarChart3 } from 'lucide-react';
import type { ComponentType } from 'react';
import { WeekPage } from './features/weekly-tracker/WeekPage';
import { LibraryPage } from './features/exercise-library/LibraryPage';
import { MonthPage } from './features/monthly-summary/MonthPage';

// OWNERSHIP: owned by Agent 1 (scaffold) only — see docs/CONTRACTS.md.
// Exactly 3 routes. Other agents build the page components these routes
// point at, but do not edit this file.

export interface NavItem {
  path: string;
  label: string;
  icon: ComponentType<{ size?: number; className?: string }>;
}

export const navItems: NavItem[] = [
  { path: '/', label: 'Week', icon: CalendarDays },
  { path: '/library', label: 'Exercise Library', icon: Dumbbell },
  { path: '/monthly', label: 'Monthly Summary', icon: BarChart3 },
];

export function AppRoutes() {
  return (
    <Routes>
      <Route path="/" element={<WeekPage />} />
      <Route path="/library" element={<LibraryPage />} />
      <Route path="/monthly" element={<MonthPage />} />
      <Route path="*" element={<Navigate to="/" replace />} />
    </Routes>
  );
}
